<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>James Routley | Feed</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="../styles.css"
      media="screen"
    />
  </head>
  <body>
    <a href="/index.html">Back</a>
    <a href="https://meaning-machine.streamlit.app">Original</a>
    <h1>Meaning Machine â€“ Visualize how LLMs break down and simulate meaning</h1>
    
    <div id="readability-page-1" class="page"><p><span>OSError</span>: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you&#39;re on Streamlit Cloud, click on &#39;Manage app&#39; in the lower right of your app).
                  </p><div>
                   <p>
                    Traceback:
                   </p>
                   <pre><p><code><p>File &#34;/mount/src/meaning-machine/app/app.py&#34;, line 41, in &lt;module&gt;
    tokenizer, model = load_bert()
                       ^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py&#34;, line 219, in __call__
    return self._get_or_create_cached_value(args, kwargs, spinner_message)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py&#34;, line 261, in _get_or_create_cached_value
    return self._handle_cache_miss(cache, value_key, func_args, func_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/streamlit/runtime/caching/cache_utils.py&#34;, line 320, in _handle_cache_miss
    computed_value = self._info.func(*func_args, **func_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/mount/src/meaning-machine/app/app.py&#34;, line 26, in load_bert
    tokenizer = AutoTokenizer.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/transformers/models/auto/tokenization_auto.py&#34;, line 819, in from_pretrained
    config = AutoConfig.from_pretrained(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/transformers/models/auto/configuration_auto.py&#34;, line 928, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/transformers/configuration_utils.py&#34;, line 631, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/transformers/configuration_utils.py&#34;, line 686, in _get_config_dict
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^</p><p>File &#34;/home/adminuser/venv/lib/python3.12/site-packages/transformers/utils/hub.py&#34;, line 441, in cached_file
    raise EnvironmentError(</p></code></p></pre>
                  </div></div>
  </body>
</html>
