<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>James Routley | Feed</title>
    <link
      rel="stylesheet"
      type="text/css"
      href="../styles.css"
      media="screen"
    />
  </head>
  <body>
    <a href="/index.html">Back</a>
    <a href="https://ntietz.com/blog/pythons-shadowing-behavior-always-surprises-me/?utm_source=atom&amp;utm_medium=feed">Original</a>
    <h1>Shadowing in Python gave me an UnboundLocalError</h1>
    
    <div id="readability-page-1" class="page"><div><p>There&#39;s this thing in Python that always trips me up.
It&#39;s not that tricky, once you know what you&#39;re looking for, but it&#39;s not intuitive for me, so I do forget.
It&#39;s that shadowing a variable can sometimes give you an UnboundLocalError!</p>
<p>It happened to me last week while working on a workflow engine with a coworker.
We were refactoring some of the code.</p>
<p>I can&#39;t share that code (yet?) so let&#39;s use a small example that illustrates the same problem.
Let&#39;s start with some working code, which we had <em>before</em> our refactoring caused a problem.
Here&#39;s some code that defines a decorator for a function, which will trigger some other functions after it runs.</p>
<pre data-lang="python"><code data-lang="python"><span>def </span><span>trigger</span><span>(</span><span>*</span><span>fns</span><span>):
</span><span>  </span><span>&#34;&#34;&#34;After the decorated function runs, it will
</span><span>  trigger the provided functions to run
</span><span>  sequentially.
</span><span>
</span><span>  You can provide multiple functions and they run
</span><span>  in the provided order.
</span><span>
</span><span>  This function *returns* a decorator, which is
</span><span>  then applied to the function we want to use to
</span><span>  trigger other functions.
</span><span>  &#34;&#34;&#34;
</span><span>
</span><span>  </span><span>def </span><span>decorator</span><span>(</span><span>fn</span><span>):
</span><span>    </span><span>&#34;&#34;&#34;This is the decorator, which takes in a
</span><span>    function and returns a new, wrapped, function
</span><span>    &#34;&#34;&#34;
</span><span>    fn._next </span><span>= </span><span>fns
</span><span>
</span><span>    </span><span>def </span><span>_wrapper</span><span>():
</span><span>      </span><span>&#34;&#34;&#34;This is the function we will now invoke
</span><span>      when we call the wrapped function.
</span><span>      &#34;&#34;&#34;
</span><span>      </span><span>fn()
</span><span>      </span><span>for </span><span>f </span><span>in </span><span>fn._next:
</span><span>        </span><span>f()
</span><span>
</span><span>    </span><span>return </span><span>_wrapper
</span><span>
</span><span>  </span><span>return </span><span>decorator
</span></code></pre>
<p>The outermost function has one job: it creates a closure for the decorator, capturing the passed in functions.
Then the decorator itself will create another closure, which captures the original wrapped function.</p>
<p>Here&#39;s an example of how it would be used.</p>
<pre data-lang="python"><code data-lang="python"><span>def </span><span>step_2</span><span>():
</span><span>  </span><span>print</span><span>(</span><span>&#34;step 2&#34;</span><span>)
</span><span>
</span><span>def </span><span>step_3</span><span>():
</span><span>  </span><span>print</span><span>(</span><span>&#34;step 3&#34;</span><span>)
</span><span>
</span><span>@</span><span>trigger</span><span>(step_2, step_3)
</span><span>def </span><span>step_1</span><span>():
</span><span>  </span><span>print</span><span>(</span><span>&#34;step 1&#34;</span><span>)
</span><span>
</span><span>step_1()
</span></code></pre>
<p>This prints out</p>
<blockquote>
<p><code>step 1</code></p>
</blockquote>
<p>Here&#39;s the code of the wrapper after I made a small change (omitting docstrings here for brevity, too).
I changed the for loop to name the loop variable <code>fn</code> instead of <code>f</code>, to shadow it and reuse that name.</p>
<pre data-lang="python"><code data-lang="python"><span>  </span><span>def </span><span>decorator</span><span>(</span><span>fn</span><span>):
</span><span>    fn._next </span><span>= </span><span>fns
</span><span>
</span><span>    </span><span>def </span><span>_wrapper</span><span>():
</span><span>      </span><span>fn()
</span><span>      </span><span>for </span><span>fn </span><span>in </span><span>fn._next:
</span><span>        </span><span>fn()
</span></code></pre>
<p>And then when we ran it, we got an error!</p>
<blockquote>
<p><code>UnboundLocalError: cannot access local variable &#39;fn&#39; where it is not associated with a value</code></p>
</blockquote>
<p>But why?
You look at the code and it&#39;s <em>defined</em>.
Right out there, it <em>is</em> bound.
If you print out the locals, trying to chase that down, you&#39;ll see that there does not, in fact, exist <code>fn</code> yet.</p>
<p>The key lies in Python&#39;s scoping rules.
Variables are defined for their entire scope, which is a module, class body, or function body.
If you define a variable within a scope, <em>anywhere</em> inside a function, then <em>that</em> variable has that name as its own for the <em>entire</em> scope.</p>
<p>The docs make this quite clear:</p>
<blockquote>
<p>If a name binding operation occurs anywhere within a code block, all uses of the name within the block are treated as references to the current block. This can lead to errors when a name is used within a block before it is bound. This rule is subtle. Python lacks declarations and allows name binding operations to occur anywhere within a code block. The local variables of a code block can be determined by scanning the entire text of the block for name binding operations. See <a href="https://docs.python.org/3/faq/programming.html#faq-unboundlocalerror">the FAQ entry on UnboundLocalError</a> for examples.</p>
</blockquote>
<p>This comes up in a few other places, too.
You can use a loop variable anywhere inside the enclosing scope, for example.</p>
<pre data-lang="python"><code data-lang="python"><span>def </span><span>my_func</span><span>():
</span><span>  </span><span>for </span><span>x </span><span>in </span><span>[</span><span>1</span><span>,</span><span>2</span><span>,</span><span>3</span><span>]:
</span><span>    </span><span>print</span><span>(x)
</span><span>
</span><span>  </span><span># this will still work!
</span><span>  </span><span># x is still defined!
</span><span>  </span><span>print</span><span>(x)
</span></code></pre>
<p>So once I saw an UnboundLocalError after I&#39;d shadowed it, I knew what was going on.
The name was used by the local for the <em>entire</em> function, not just after it was initialized!
I&#39;m used to shadowing <em>being</em> the idiomatic thing in Rust, then had to recalibrate for writing Python again.
It made sense once I remembered what was going on, but I think it&#39;s one of Python&#39;s little rough edges.</p>
<hr/>
</div><p>
  If you&#39;re looking to grow more effective as a software engineer, please consider my <a href="https://batsov.com/coaching/">coaching services</a>.
  </p></div>
  </body>
</html>
